In [20]:
%pylab inline
import maxflow
from skimage.io import imread

Populating the interactive namespace from numpy and matplotlib


/home/saket/anaconda3/lib/python3.5/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['poisson']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [12]:
from scipy.stats import poisson

In [13]:
x = poisson.pmf(np.arange(0, 256), 130)

In [18]:
x[[130, 100, 10]]

array([3.49671307e-02, 9.24802358e-04, 1.32247613e-42])

In [19]:
x[[130]]

array([0.03496713])

In [9]:
a  = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.stack([a, b], axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
np.stack([a, b], axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [11]:
np.stack([a, b], axis=2)

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [21]:
img = imread('../data/images/i2.png')

In [22]:
g = maxflow.Graph[int]()
# Add the nodes. nodeids has the identifiers of the nodes in the grid.
nodeids = g.add_grid_nodes(img.shape)
# Add non-terminal edges with the same capacity.
g.add_grid_edges(nodeids, 50)
# Add the terminal edges. The image pixels are the capacities
# of the edges from the source node. The inverted image pixels
# are the capacities of the edges to the sink node.
g.add_grid_tedges(nodeids, img, 255-img)

In [23]:
img.shape

(1536, 2048, 3)

In [24]:
import pygco